# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Screen reader Demo
  items:
    - label: The Basics - Role, Name, Value and State
      link:  '/principles'
    - label: Links and Resources
      link:  '/resources'
